version: '3.8'
services:
  db:
    image: 'postgres:14.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
  # backend:
  #   container_name: backend
  #   build: ./backend
  #   ports:
  #     - 8000:8000
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@db/postgres
  #     - SECRET_API_KEY=akljnv13bvi2vfo0b0bw  
  #   depends_on:
  #     - db
